/// @description also handles steam
fmod_init(32);
fmod_set_num_listeners(1);

var banks = ["sound/Desktop/Master.strings.bank", "sound/Desktop/Master.bank", "sound/Desktop/music.bank", "sound/Desktop/sfx.bank"];
trace("Loading banks!");
for (var i = 0; i < array_length(banks); i++)
{
	var b = working_directory + banks[i];
	if (!fmod_bank_load(b, false))
		trace("Could not load bank: ", b);
	else if (!fmod_bank_load_sample_data(b))
		trace("Could not load sample data: ", b);
}
global.sound_map = ds_map_create();
global.steam_api = false;

#region macros

// function aliases
#macro sound_play fmod_event_one_shot
#macro sound_play_3d fmod_event_one_shot_3d
#macro sound_get_length fmod_event_get_length
#macro sound_pause_all fmod_event_instance_set_paused_all

#macro sound_instance_create fmod_event_create_instance
#macro sound_instance_destroy fmod_event_instance_release
#macro sound_instance_play fmod_event_instance_play
#macro sound_instance_stop fmod_event_instance_stop
#macro sound_instance_move fmod_event_instance_set_3d_attributes
#macro sound_instance_parameter fmod_event_instance_set_parameter
#macro sound_instance_get_parameter fmod_event_instance_get_parameter
#macro sound_instance_is_playing fmod_event_instance_is_playing
#macro sound_instance_pause fmod_event_instance_set_paused
#macro sound_instance_is_paused fmod_event_instance_get_paused
#macro sound_instance_track_position fmod_event_instance_get_timeline_pos

// music
#macro mu_entrancetitle "event:/music/w1/entrancetitle"
#macro mu_medievaltitle "event:/music/w1/medievaltitle"
#macro mu_ruintitle "event:/music/w1/ruintitle"
#macro mu_dungeontitle "event:/music/w1/dungeontitle"
#macro mu_deserttitle "event:/music/w2/deserttitle"
#macro mu_saloontitle "event:/music/w2/saloontitle"
#macro mu_graveyardtitle "event:/music/w2/graveyardtitle"
#macro mu_farmtitle "event:/music/w2/farmtitle"
#macro mu_golftitle "event:/music/w3/golftitle"
#macro mu_foresttitle "event:/music/w3/foresttitle"
#macro mu_spacetitle "event:/music/w3/spacetitle"
#macro mu_beachtitle "event:/music/w3/beachtitle"
#macro mu_industrialtitle "event:/music/w4/industrialtitle"
#macro mu_freezertitle "event:/music/w4/freezertitle"
#macro mu_sewertitle "event:/music/w4/sewertitle"
#macro mu_streettitle "event:/music/w4/streettitle"
#macro mu_kidspartytitle "event:/music/w5/kidspartytitle"
#macro mu_wartitle "event:/music/w5/wartitle"
#macro mu_chateautitle "event:/music/w5/chateautitle"

#macro mu_timesup "event:/music/timesup"
#macro mu_finalrank "event:/music/finalrank"

// sounds
#macro sfx_step "event:/sfx/ui/step"

#macro sfx_voice_peppinoangryscream "event:/sfx/voice/peppinoangryscream"
#macro sfx_voice_peppinoangryscream2 "event:/sfx/voice/peppinoangryscream2"
#macro sfx_voice_noisepositive "event:/sfx/voice/noisepositive"
#macro sfx_voice_noisescream "event:/sfx/voice/noisescream"
#macro sfx_voice_gushurt "event:/sfx/voice/gushurt"
#macro sfx_voice_ok "event:/sfx/voice/ok"
#macro sfx_voice_vigiintro "event:/sfx/voice/vigiintro"
#macro sfx_voice_vigiduel "event:/sfx/voice/vigiduel"
#macro sfx_voice_vigiangry "event:/sfx/voice/vigiangry"
#macro sfx_voice_myea "event:/sfx/voice/myea"
#macro sfx_voice_pizzahead "event:/sfx/voice/pizzahead"
#macro sfx_voice_fakepepscream "event:/sfx/voice/fakepepscream"
#macro sfx_voice_fakepeppositive "event:/sfx/voice/fakepeppositive"
#macro sfx_voice_peppermanlaugh "event:/sfx/voice/peppermanlaugh"
#macro sfx_voice_peppermansnicker "event:/sfx/voice/peppermansnicker"
#macro sfx_voice_peppermanscared "event:/sfx/voice/peppermanscared"
#macro sfx_voice_brickok "event:/sfx/voice/brickok"
#macro sfx_voice_yodeling "event:/sfx/voice/yodeling"
#macro sfx_voice_pigphoto "event:/sfx/voice/pigphoto"
#macro sfx_voice_muffledscream "event:/sfx/voice/muffledscream"

#macro sfx_jump "event:/sfx/pep/jump"
#macro sfx_punch "event:/sfx/pep/punch"
#macro sfx_screamboss "event:/sfx/pep/screamboss"
#macro sfx_pistolshot "event:/sfx/pep/pistolshot"
#macro sfx_revolverbigshot "event:/sfx/pep/revolverBIGshot"
#macro sfx_groundpound "event:/sfx/pep/groundpound"
#macro sfx_bumpwall "event:/sfx/pep/bumpwall"
#macro sfx_shotgunload "event:/sfx/pep/shotgunload"
#macro sfx_hurt "event:/sfx/pep/hurt"
#macro sfx_slip "event:/sfx/pep/slip"
#macro sfx_slipend "event:/sfx/pep/slipend"
#macro sfx_slipbump "event:/sfx/pep/slipbump"
#macro sfx_stepinshit "event:/sfx/pep/stepinshit"
#macro sfx_playerstep "event:/sfx/pep/step"
#macro sfx_taunt "event:/sfx/pep/taunt"
#macro sfx_break "event:/sfx/pep/break"
#macro sfx_machslideboost "event:/sfx/pep/machslideboost"
#macro sfx_splat "event:/sfx/pep/splat"
#macro sfx_superjumpcancel "event:/sfx/pep/superjumpcancel"
#macro sfx_backslide "event:/sfx/pep/backslide"
#macro sfx_supertaunt "event:/sfx/pep/supertaunt"
#macro sfx_gravecorpsestart "event:/sfx/pep/gravecorpsestart"
#macro sfx_cheesejump "event:/sfx/pep/cheesejump"
#macro sfx_box "event:/sfx/pep/box"
#macro sfx_jetpackjump "event:/sfx/pep/jetpackjump"
#macro sfx_suplexdash "event:/sfx/pep/suplexdash"

#macro sfx_pepperman_shoulderbash "event:/sfx/pepperman/shoulderbash"
#macro sfx_pepperman_groundpound "event:/sfx/pepperman/groundpound"
#macro sfx_pepperman_groundpoundjump "event:/sfx/pepperman/groundpoundjump"
#macro sfx_pepperman_groundpoundbump "event:/sfx/pepperman/groundpoundbump"
#macro sfx_pepperman_turn "event:/sfx/pepperman/turn"
#macro sfx_pepperman_artdude "event:/sfx/pepperman/artdude"

#macro sfx_spin "event:/sfx/noise/spin"
#macro sfx_skatestart "event:/sfx/noise/skatestart"
#macro sfx_skateloop "event:/sfx/noise/skateloop"
#macro sfx_skateturn "event:/sfx/noise/skateturn"
#macro sfx_jetpackstart "event:/sfx/noise/jetpackstart"
#macro sfx_jetpackspin "event:/sfx/noise/jetpackspin"
#macro sfx_jetpackloop "event:/sfx/noise/jetpackloop"
#macro sfx_balloon "event:/sfx/noise/balloon"
#macro sfx_droptrap "event:/sfx/noise/droptrap"
#macro sfx_fightball "event:/sfx/noise/fightball"
#macro sfx_machslide "event:/sfx/noise/machslide"
#macro sfx_pogo "event:/sfx/noise/pogo"
#macro sfx_noisecrusher "event:/sfx/noise/noisecrusher"

#macro sfx_vigilante_throw "event:/sfx/vigilante/throw"
#macro sfx_vigilante_flamethrower "event:/sfx/vigilante/flamethrower"
#macro sfx_vigilante_mach1 "event:/sfx/vigilante/mach1"
#macro sfx_vigilante_slide "event:/sfx/vigilante/slide"
#macro sfx_vigilante_uziprep "event:/sfx/vigilante/uziprep"
#macro sfx_vigilante_order "event:/sfx/vigilante/order"
#macro sfx_vigilante_finalshot "event:/sfx/vigilante/finalshot"

#macro sfx_fakepep_bodyslam "event:/sfx/fakepep/bodyslam"
#macro sfx_fakepep_mach "event:/sfx/fakepep/mach"
#macro sfx_fakepep_superjump "event:/sfx/fakepep/superjump"
#macro sfx_fakepep_superjumpclonerelease "event:/sfx/fakepep/superjumpclonerelease"
#macro sfx_fakepep_grab "event:/sfx/fakepep/grab"
#macro sfx_fakepep_headoff "event:/sfx/fakepep/headoff"
#macro sfx_fakepep_flailing "event:/sfx/fakepep/flailing"
#macro sfx_fakepep_deform "event:/sfx/fakepep/deform"
#macro sfx_fakepep_reform "event:/sfx/fakepep/reform"
#macro sfx_fakepep_headthrow "event:/sfx/fakepep/headthrow"
#macro sfx_fakepep_taunt "event:/sfx/fakepep/taunt"
#macro sfx_fakepep_chase "event:/sfx/fakepep/chase"

#macro sfx_pizzaface_shower "event:/sfx/pizzaface/shower"
#macro sfx_pizzaface_ram "event:/sfx/pizzaface/ram"
#macro sfx_pizzaface_spit "event:/sfx/pizzaface/spit"
#macro sfx_pizzaface_laugh "event:/sfx/pizzaface/laugh"
#macro sfx_pizzaface_jump "event:/sfx/pizzaface/jump"
#macro sfx_pizzaface_open "event:/sfx/pizzaface/open"
#macro sfx_pizzaface_moving "event:/sfx/pizzaface/moving"
#macro sfx_pizzahead_haywire "event:/sfx/pizzahead/haywire"
#macro sfx_pizzahead_jump "event:/sfx/pizzahead/jump"
#macro sfx_pizzahead_bigpunch "event:/sfx/pizzahead/bigpunch"
#macro sfx_pizzahead_swinging "event:/sfx/pizzahead/swinging"
#macro sfx_pizzahead_swingstart "event:/sfx/pizzahead/swingstart"
#macro sfx_pizzahead_bigpunchstart "event:/sfx/pizzahead/bigpunchstart"
#macro sfx_pizzahead_giantstomp "event:/sfx/pizzahead/giantstomp"
#macro sfx_pizzahead_tvthrow "event:/sfx/pizzahead/tvthrow"
#macro sfx_pizzahead_spin "event:/sfx/pizzahead/spin"
#macro sfx_pizzahead_grablevel "event:/sfx/pizzahead/grablevel"
#macro sfx_pizzahead_fishing "event:/sfx/pizzahead/fishing"
#macro sfx_pizzahead_ratball "event:/sfx/pizzahead/ratball"
#macro sfx_pizzahead_step "event:/sfx/pizzahead/step"
#macro sfx_pizzahead_medievalbringup "event:/sfx/pizzahead/medievalbringup"
#macro sfx_pizzahead_uzi "event:/sfx/pizzahead/uzi"
#macro sfx_pizzahead_throw "event:/sfx/pizzahead/throw"
#macro sfx_pizzahead_medievalprojectile "event:/sfx/pizzahead/medievalprojectile"
#macro sfx_pizzahead_recover "event:/sfx/pizzahead/recover"

#macro sfx_enemyscream "event:/sfx/voice/enemyrarescream"
#macro sfx_killingblow "event:/sfx/enemies/killingblow"
#macro sfx_rancherpistol "event:/sfx/enemies/rancherpistol"
#macro sfx_enemyprojectile "event:/sfx/enemies/projectile"
#macro sfx_minijohnpunch "event:/sfx/enemies/minijohnpunch"
#macro sfx_pizzardelectricity "event:/sfx/enemies/pizzardelectricity"
#macro sfx_coughing "event:/sfx/enemies/coughing"
#macro sfx_ufolivelaser "event:/sfx/enemies/ufolivelaser"
#macro sfx_charge "event:/sfx/enemies/charge"
#macro sfx_killenemy "event:/sfx/enemies/kill"
#macro sfx_batwing "event:/sfx/enemies/batwing"
#macro sfx_presentfall "event:/sfx/enemies/presentfall"
#macro sfx_jumpscare "event:/sfx/enemies/jumpscare"
#macro sfx_badrat "event:/sfx/enemies/badrat"
#macro sfx_piranha "event:/sfx/enemies/piranha"
#macro sfx_ninjakicks "event:/sfx/enemies/ninjakicks"
#macro sfx_pickledance "event:/sfx/enemies/pickledance"
#macro sfx_cannongoblin "event:/sfx/enemies/cannongoblin"
#macro sfx_noisegoblinbow "event:/sfx/enemies/noisegoblinbow"
#macro sfx_robotslapsteam "event:/sfx/enemies/robotslapsteam"
#macro sfx_banditochicken "event:/sfx/enemies/banditochicken" // LEFT IT HERE
#macro sfx_monsters_cheese "event:/sfx/monsters/cheeseloop"
#macro sfx_monsters_puppet "event:/sfx/monsters/puppetfly"

#macro sfx_barrelslope "event:/sfx/barrel/slope"
#macro sfx_barrelstart "event:/sfx/barrel/start"
#macro sfx_boxxedstep "event:/sfx/boxxed/step"
#macro sfx_boxxedflap "event:/sfx/boxxed/flap"
#macro sfx_mortdead "event:/sfx/mort/mortdead"
#macro sfx_mortside "event:/sfx/mort/mortside"
#macro sfx_mortup "event:/sfx/mort/mortup"
#macro sfx_mortdown "event:/sfx/mort/down"
#macro sfx_mortdoublejump "event:/sfx/mort/doublejump"
#macro sfx_mortpickup "event:/sfx/mort/mortpickup"
#macro sfx_firemouth_dash "event:/sfx/firemouth/dash"
#macro sfx_firemouth_jump "event:/sfx/firemouth/jump"
#macro sfx_cheesedstep "event:/sfx/cheese/step"
#macro sfx_cheesedjump "event:/sfx/cheese/jump"
#macro sfx_cheesedground "event:/sfx/cheese/ground"
#macro sfx_knightdown "event:/sfx/knight/down"
#macro sfx_antigravstart "event:/sfx/antigrav/start"
#macro sfx_antigravend "event:/sfx/antigrav/end"
#macro sfx_antigravbump "event:/sfx/antigrav/bump"
#macro sfx_ratmount_walljump1 "event:/sfx/ratmount/walljump1"
#macro sfx_ratmount_walljump2 "event:/sfx/ratmount/walljump2"
#macro sfx_weeniestart "event:/sfx/weenie/start"

#macro sfx_rat_deflateeat "event:/sfx/rat/deflateeat"
#macro sfx_rat_grabeat "event:/sfx/rat/grabeat"
#macro sfx_bossdefeattonk "event:/sfx/misc/bossdefeattonk"
#macro sfx_windloop "event:/sfx/misc/windloop"
#macro sfx_explosion "event:/sfx/misc/explosion"
#macro sfx_breakblock "event:/sfx/misc/breakblock"
#macro sfx_golfpunch "event:/sfx/misc/golfpunch"
#macro sfx_transfo "event:/sfx/misc/transfo"
#macro sfx_detransfo "event:/sfx/misc/detransfo"
#macro sfx_waterslidesplash "event:/sfx/misc/waterslidesplash"
#macro sfx_watersplash "event:/sfx/misc/watersplash"
#macro sfx_checkpoint "event:/sfx/misc/checkpoint"
#macro sfx_blackoutpunch "event:/sfx/misc/blackoutpunch"
#macro sfx_golfbump "event:/sfx/misc/golfbump"
#macro sfx_collect "event:/sfx/misc/collect"
#macro sfx_bellcollect "event:/sfx/misc/bellcollect"
#macro sfx_collectpizza "event:/sfx/misc/collectpizza"
#macro sfx_collecttoppin "event:/sfx/misc/collecttoppin"
#macro sfx_versusscreen "event:/sfx/misc/versusscreen"
#macro sfx_cardcollect "event:/sfx/misc/cardcollect"
#macro sfx_bosskey "event:/sfx/misc/bosskey"
#macro sfx_switchstart "event:/sfx/misc/switchstart"
#macro sfx_switchend "event:/sfx/misc/switchend"
#macro sfx_bubblestation "event:/sfx/misc/bubblestation"
#macro sfx_timerbegin "event:/sfx/misc/timerbegin"
#macro sfx_timercount "event:/sfx/misc/timercount"
#macro sfx_timerend "event:/sfx/misc/timerend"
#macro sfx_piranhabite "event:/sfx/misc/piranhabite"
#macro sfx_mushroombounce "event:/sfx/misc/mushroombounce"
#macro sfx_mrstickhat "event:/sfx/misc/mrstickhat"
#macro sfx_door "event:/sfx/misc/door"
#macro sfx_elevatorstart "event:/sfx/misc/elevatorstart"
#macro sfx_keyunlock "event:/sfx/misc/keyunlock"
#macro sfx_teleporterstart "event:/sfx/misc/teleporterstart"
#macro sfx_teleporterend "event:/sfx/misc/teleporterend"
#macro sfx_lap2start "event:/sfx/misc/lap2start"
#macro sfx_cross "event:/sfx/misc/cross"
#macro sfx_cow "event:/sfx/misc/cow"
#macro sfx_rockbreak "event:/sfx/misc/rockbreak"
#macro sfx_dashpad "event:/sfx/misc/dashpad"
#macro sfx_taxibeep "event:/sfx/misc/taxibeep"
#macro sfx_taximove "event:/sfx/misc/taximove"
#macro sfx_policesiren "event:/sfx/misc/policesiren"
#macro sfx_cheers "event:/sfx/misc/cheers"
#macro sfx_honkhonk "event:/sfx/misc/honkhonk"
#macro sfx_secretfound "event:/sfx/misc/secretfound"
#macro sfx_toppinhelp "event:/sfx/misc/toppinhelp"
#macro sfx_foundtreasure "event:/sfx/misc/foundtreasure"
#macro sfx_breakmetal "event:/sfx/misc/breakmetal"
#macro sfx_balloonpop "event:/sfx/misc/balloonpop"
#macro sfx_bottlepop "event:/sfx/misc/bottlepop"
#macro sfx_superspring "event:/sfx/misc/superspring"
#macro sfx_pepbotkick "event:/sfx/misc/pepbotkick"
#macro sfx_star "event:/sfx/ending/star"
#macro sfx_towercollapsetrack "event:/sfx/ending/towercollapsetrack"
#macro sfx_towercollapse "event:/sfx/ending/towercollapse"

#endregion
